---
name: VyOS Rolling

on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * *

env:
  VYOS_URL: https://github.com/vyos/vyos-build
  VYOS_BRANCH: sagitta
  VYOS_ARCH: amd64
  VYOS_BUILD_BY: 98030736+rosey-bot[bot]@users.noreply.github.com
  VYOS_BUILD_TYPE: release
  VYOS_VERSION: 1.4-rolling

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      # Need permission to write to the Releases tab now.
      # https://github.com/ncipollo/release-action/issues/208.
      contents: write
    container:
      image: vyos/vyos-build:sagitta
      options: --privileged
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: generate-token
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Setup variables
        id: vars
        run: |
          build_date=$(date +%Y%m%d%H%M)
          echo "tag-name=${{ env.VYOS_VERSION }}-${build_date}" >> "$GITHUB_OUTPUT"
          echo "iso-name=${{ env.VYOS_VERSION }}-${build_date}-${{ env.VYOS_ARCH }}" >> "$GITHUB_OUTPUT"

      - name: Clone vyos-build
        run: git clone -b ${{ env.VYOS_BRANCH }} --single-branch ${{ env.VYOS_URL }}

      - name: Download sops deb
        uses: robinraju/release-downloader@efa4cd07bd0195e6cc65e9e30c251b49ce4d3e51 # v1.8
        with:
          repository: mozilla/sops
          latest: true
          fileName: "*amd64.deb"
          out-file-path: vyos-build/packages

      - name: Configure
        working-directory: vyos-build
        run: |
          sudo make clean
          sudo ./build-vyos-image iso \
              --architecture ${{ env.VYOS_ARCH }} \
              --build-by ${{ env.VYOS_BUILD_BY }} \
              --build-type ${{ env.VYOS_BUILD_TYPE }} \
              --build-comment "VyOS with additional packages" \
              --version ${{ steps.vars.outputs.tag-name }} \
              --custom-package "git" \
              --custom-package "iptables" \
              --custom-package "jo" \
              --custom-package "moreutils" \
              --custom-package "python3-venv" \
              --custom-package "tree"

      - name: Create release with artifact
        uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5 # v1.13.0
        with:
          token: "${{ steps.generate-token.outputs.token }}"
          tag: "v${{ steps.vars.outputs.tag-name }}"
          artifacts: "./vyos-build/build/vyos-${{ steps.vars.outputs.iso-name }}.iso"
          artifactErrorsFailBuild: true
          body: |
            Official VyOS Changelog:
            https://docs.vyos.io/en/latest/changelog/1.4.html

      - name: Delete orphaned release
        if: failure()
        uses: dev-drprasad/delete-tag-and-release@5eafd8668311bf3e4d6c1e9898f32a317103de68 # v0.2.1
        with:
          github_token: "${{ steps.generate-token.outputs.token }}"
          tag_name: "v${{ steps.vars.outputs.tag-name }}"
          delete_release: true

      - name: Prune old releases
        if: always()
        uses: dev-drprasad/delete-older-releases@5494cd8b61c31b3c7a15f6267901195ec7df64e8 # v0.3.2
        with:
          keep_latest: 120
          delete_tags: true
        env:
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
